# Generated by Django 4.1.6 on 2023-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Indigo', max_length=30)),
                ('cc', models.IntegerField(default=500, max_length=6)),
                ('brand', models.CharField(default='Indian', max_length=30)),
            ],
        ),
    ]
